
export const types = {
    USUARIOS_CARGADOS: 'USUARIOS_CARGADOS',
    ACTIVAR_CHAT: 'ACTIVAR_CHAT',
    NUEVO_MENSAJE: 'NUEVO_MENSAJE',
    CARGAR_MENSAJES: 'CARGAR_MENSAJES',
    PURGAR_CHATINFO: 'PURGAR_CHATINFO'
}

